#pragma once
#include "Board.h"
#include <SFML/Graphics.hpp>
#include "Menu.h"
#include "Player.h"
#include "PlayerUI.h"
#include "HexTile.h"
#include "Buildable.h"
#include "Knight.h"
#include "Trade.h"
#include "Cards.h" 
#include "SimpleButton.h"
#include "UIButton.h"
#include "Menago.h"
#include "Game.h"
#include <memory>
#include <vector>
#include <filesystem>
#include <functional>
#include <ranges>
#include <cmath>
#include <thread>
#include <mutex>
#include <array>
#include <iostream>
#include <map>
#include <SFML/Window.hpp>

